### ISSUE TITLE
Applied Energistics 2 support

### ISSUE THREAD

**Issue by totyaxy** [Darkhax-Minecraft/WAWLA#102]
Hi!

I'd like to see the Applied Energistics 2 mod (wire) channel informations, if possible.

Thank you.

**Comment by darkhax** [comment]
Applied Energistics already provides support on their own. https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c2d18ce0133a27d54a16d95a4f89f38dbc1a1bb1/src/main/java/appeng/integration/modules/waila/PartWailaDataProvider.java

**Comment by totyaxy** [comment]
Hi, thank you! 

You are right, so as I see, the main problem was, not all the cable put channel information, so this is AE2 problem.
