### ISSUE TITLE
Not Working on Galacticraft

### ISSUE THREAD

**Issue by Feky** [Darkhax-Minecraft/WAWLA#103]
It's not working on Galacticraft for some reason. It's there but in mod folder but not showing block names at all in game.

https://minecraft.curseforge.com/projects/lapitos-galacticraft

:/

**Comment by darkhax** [comment]
This modpack hasn't installed Hwyla or Waila, which is needed to use this mod.

**Comment by Feky** [comment]
Ok thanks! Will try with that!

**Comment by Feky** [comment]
Thanks again. Installed Hwyla and its working. Will contact dev to add Hwyla to next update :)
