### ISSUE TITLE
Crash issue with Armor Toughness Bar??? (Project Ozone 3)

### ISSUE THREAD

**Issue by Leo40Git** [Darkhax-Minecraft/WAWLA#107]
uhh??? i have no idea

crash log: https://pastebin.com/CSEzfZfH

using PO3 v3.0.38 with toughness bar v2.1 added

**Comment by Leo40Git** [comment]
issue on ATB's repo: https://github.com/Tfarcenim/Toughness-Bar/issues/4

**Comment by darkhax** [comment]
The mod in the crash log is WAILA, this repo is for WAWLA. You're looking for the HWYLA repo.

**Comment by Leo40Git** [comment]
oops
