### ISSUE TITLE
[1.12.2] Not compatible with SpongeForge

### ISSUE THREAD

**Issue by Brycey92** [Darkhax-Minecraft/WAWLA#108]
Since the Forge version this mod is compiled against has been updated past 2768, the mod is no longer compatible with SpongeForge, which requires Forge 2768.

**Comment by darkhax** [comment]
Thank you for the report. I don't offer or support compatibility with SpongeForge. Hopefully they can fix/update their project to work with newer Forge versions. The new versions of Wawla are primarily translation updates so you can safely revert to older versions. I am not planning to add new features until the 1.13 version of the mod so you won't be missing out on any major features.

**Comment by Brycey92** [comment]
Thanks for the info!
