### ISSUE TITLE
Break Percentage Missing

### ISSUE THREAD

**Issue by warderbrad** [Darkhax-Minecraft/WAWLA#112]
Hello,

I am sure this is a setting or mod interaction but the break percentage is not displaying. 

Please let me know what info I can provide that would help to diagnose this issue.

Thank you,

**Comment by Darkhax** [comment]
Thanks for the report. Sorry if this seems condescending, but are you sure you actually have Wawla installed? The mod that adds the info HUD is called Hwyla, and Wawla just adds additional information. People frequently come to me with issues but they only have one of the mods installed, while both are needed. 

If you do have both mods, there is no keybind to accidentally disable it. You could try checking the `~/config/wawla.cfg` file to see if `breakprogress` is set to true.
