### ISSUE TITLE
[1.12.2] Securiy Craft

### ISSUE THREAD

**Issue by LeithHussain** [Darkhax-Minecraft/WAWLA#115]
WAWLA shows the passcode of password protected chest, keypad, password protected furnance. this defeats the point of having a secure chest as anyone can see the password of the said chest if they look at it, i believe it has something to do with debug entity information or Shows debug entity information, i want to see the owner of the chest and simular information without reveling the passcode. can you do something like tinkers construct mine where the debug information is hidden

**Comment by Darkhax** [comment]
WAWLA doesn't have any built in support for Security Craft. The only way I could see this information being revealed is if the player is using the debug NBT viewer feature. The proper fix would be for Security Craft to store the password somewhere that isn't in plain sight, or practice proper data security and only store a hash of the password which is combined with some server-side salt value. 

I can look into disabling this specific feature for players who are not in creative mode which will also solve this, however it really is on Security Craft to keep passwords secure.

**Comment by Darkhax** [comment]
I've spoken to the SecurityCraft team about improving their own security, whether or not they do is up to them. As for the NBT debug feature in this mod, it is only enabled for Creative Mode players. Security Craft has their own features to show the password, but they say it's only visible to the owner.
