### ISSUE TITLE
Zombie Villager Profession?

### ISSUE THREAD

**Issue by DoomRater** [Darkhax-Minecraft/WAWLA#116]
Currently WAWLA shows villager profession, but it seems as of 1.12.2 they also have professions that don't change when they are zombified. I'd love to know what profession a villager has before I cure him as that would speed up my diversity project by quite a bit.

**Comment by Darkhax** [comment]
Thanks for the request. This is already a feature and is confirmed working on 1.12.2. Please make sure you are using the latest version of the mod. 

![image](https://user-images.githubusercontent.com/2250798/77895548-79910800-7266-11ea-997c-1c1b72743d53.png)
