### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by H0bbitBaron** [Darkhax-Minecraft/WAWLA#118]
Hi, can i somehow fix Russian translation?

tooltip.wawla.chest=Сундук -> tooltip.wawla.chest=Нагрудник
tooltip.wawla.generic.breedingitem=Читабельный -> tooltip.wawla.generic.breedingitem=Размножаем

**Comment by Darkhax** [comment]
Thanks for requesting the updates, I have added them to the mod. You can also create a pull request on GitHub to make new changes.
