### ISSUE TITLE
Crashing inside the forge loader

### ISSUE THREAD

**Issue by ChadowT98** [Darkhax-Minecraft/WAWLA#119]
Hello,

I'm on 1.7.10 and I seem to have an issue  where the game crashes inside the forgeloader.
I have this message in the logs : 
[11:49:53] [Client thread/ERROR]: The mod wawla (What Are We Looking At) requires mods [Waila] to be available

Even though Waila is installed and working whitout WAWLA

[latest.log](https://github.com/Darkhax-Minecraft/WAWLA/files/4408292/latest.log)

**Comment by Darkhax** [comment]
The log is correct, that mod is not loaded when Wawla is being loaded. Either way 1.7.10 is no longer supported as it is 5 years, 9 months, and 5 days old. 

https://www.howoldisminecraft1710.today/
