### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by dukeschnauzer** [Darkhax-Minecraft/WAWLA#122]
i installed this mod with WAILA and WAWLA but none of it are showing the little bubble icon when im looking at it, im using galactic craft, aether, twilight forest and galaxy space and Just Enought Items, please help because i dont know whats the problem

it was working before but now its not

**Comment by Darkhax** [comment]
Which version of the mod are you using? You probably want to use Hwyla and not Waila.

**Comment by MineTug** [comment]
I'm in minecraft 1.12.2 so waila and hwyla doesn't work otherwise my version of wawla is 2.6.275
