### ISSUE TITLE
[1.15.2] No Harvestability shown?

### ISSUE THREAD

**Issue by realTIMematrix** [Darkhax-Minecraft/WAWLA#124]
Hi,

I'm using:

Forge: 31.1.63
Hwyla-forge-1.10.8-B72_1.15.2.jar
WAWLA-1.15.2-3.0.1.jar

No matter what I do I can't see the required tools like in The One Probe.
I also can't find options to turn this ON/OFF

I also noticed that in the in-game options from WAWLA two options are unreadabe.
They have text like this: `config.waila.plugin_wawla.b` and `config.waila.plugin_wawla.t`
I set these two options to FALSE and all other to TRUE so I can identify this options in the configfile. The two options are "block_ench_power" and "table_ench_power" which are not shown correct in the in-game config options.

**Comment by Darkhax** [comment]
The harvestability feature was not included in the port. A lot has changed with regards to the harvestability and it needs to be rewritten. The entity equipment info is also missing currently. 

The missing config localizations for those options has been added to the next version.
