### ISSUE TITLE
Breedable does not function in client with vanilla server

### ISSUE THREAD

**Issue by xbony2** [Darkhax-Minecraft/WAWLA#125]
So if my client is modded but the server isn't, then looking at any animal, breedable or not, WAWLA will say the animal is breedable.

This is not an issue in single player.

I imagine it might be impossible for WAWLA to find this information without WAWLA on the server. If so, then no Breedable information should show up in my opinion.

edit: whoops, to clarify this is with 1.15.2 and WAWLA version 3.0.2, and Minecraft Forge 31.1.41.

**Comment by Darkhax** [comment]
Thanks for reporting. You are correct, this is an issue where the client doesn't have access to this data and the server is not able to send it over. The new version should hide the tooltips if it is unable to show them.
