### ISSUE TITLE
Crash without HWYLA instead of missing dependency message

### ISSUE THREAD

**Issue by C0rn3j** [Darkhax-Minecraft/WAWLA#126]
This is on MC 1.15.2

I downloaded the wrong version of HWYLA (fabric), and the game crashed with a WAWLA error.

What I think should have happened is that WAWLA should've thrown an error about a missing dependency instead, like most other mods do.

Botania missing dependency example:
![image](https://user-images.githubusercontent.com/1641362/82116599-48638d00-976b-11ea-8909-9dd1fac838fa.png)

Log: https://haste.rys.pw/raw/sinebexine

**Comment by Darkhax** [comment]
This issue was fixed in https://github.com/Darkhax-Minecraft/WAWLA/commit/c62d3e2e76737115dce474bfb6e4634ba7bb7db3 and https://github.com/Darkhax-Minecraft/WAWLA/commit/59c8604daad575748c4911495a6081e84826f937
