### ISSUE TITLE
1.12.2 Waila (Hwyla) Not showing up (Sevtech Ages)

### ISSUE THREAD

**Issue by InsaintyAi** [Darkhax-Minecraft/WAWLA#127]
Hello and im sorry if this is a redundant issue to be solved. I have been playing SevTech Ages with some friends on a 1.12.2 server and recently I, not sure about others, have been having an issue where the bubble at the top of the screen doesnt work. It just doesnt show up when I look at a block or an animal or really anything. Im not sure why it just stopped working all of a sudden. Sorry if im not being specific enough.

**Comment by Darkhax** [comment]
SevTech locks waila behind pack progression. This mod doesn't add the info bubble or control it at all, it just adds info to it.
