### ISSUE TITLE
Permission to port

### ISSUE THREAD

**Issue by smujaddid** [Darkhax-Minecraft/WAWLA#128]
Hi, Darkhax!

Considering you are not planning to port your mods for fabric loader, through this, I'm asking permission to port your mods, primarily WAWLA and some others, to fabric version of your mods.
I intend to release them to CurseForge when they are ready.

If you decided to disallow it, then I shall not continue my attempt.

Thanks!

**Comment by Darkhax** [comment]
Hello, 

I do not wish for my mods to be available for Fabric in any way, including 3rd party or unofficial ports.

**Comment by NebelNidas** [comment]
> I do not wish for my mods to be available for Fabric in any way

That's… a very stupid decision, especially since Fabric is gaining more and more traction and becomes increasingly popular amongst both users and modders. Could you explain your reasoning?
