### ISSUE TITLE
1.16 with fabric

### ISSUE THREAD

**Issue by mcailac** [Darkhax-Minecraft/WAWLA#130]
Hello, I saw #129. 
My question is: did you plan to work on a 1.16 fabric version? I love your mod, it will be really helpful to have access to it in 1.16 😋 
Anyway, thank you for this mod! Your work is awesome.

PS: when I say 1.16, of course I mean 1.16, 1.16.1 and every minor version of 1.16^^

Edit: bookshelf doesn't support fabric for now so I don't know if that's a hindrance to you.

**Comment by Enderminer** [comment]
Why not forge?
There's a 1.16.1 forge version of Hwyla and it'd be easier to update considering bookshelf already has a 1.16.1 version.

**Comment by mcailac** [comment]
> Why not forge?
> There's a 1.16.1 forge version of Hwyla and it'd be easier to update considering bookshelf already has a 1.16.1 version.

Because I'm using forge ^^ It's better that forge for my needs 😋

**Comment by Enderminer** [comment]
> > Why not forge?
> > There's a 1.16.1 forge version of Hwyla and it'd be easier to update considering bookshelf already has a 1.16.1 version.
> 
> Because I'm using forge ^^ It's better that forge for my needs 😋

I don't think you understood what I was saying.
You said you wanted a 1.16 fabric version of WAWLA, I was asking why not use forge rather than fabric because it would be easier to update.
Apologies if I wasn't clear before.

**Comment by mcailac** [comment]
> > > Why not forge?
> > > There's a 1.16.1 forge version of Hwyla and it'd be easier to update considering bookshelf already has a 1.16.1 version.
> > 
> > 
> > Because I'm using forge ^^ It's better that forge for my needs 😋
> 
> I don't think you understood what I was saying.
> You said you wanted a 1.16 fabric version of WAWLA, I was asking why not use forge rather than fabric because it would be easier to update.
> Apologies if I wasn't clear before.

Sorry I did a typo when writing... I meant to say that I'm NOT using forge haha, I use mods that require fabric so I can't use forge anymore. I think modding in minecraft becomes more and more complex every year.

Or I just don't know that fabric and forge can be installed on a same instance? If so please tell me! It will be really helpful.

<details>
  <summary>[spoiler] Here is my list of mods I use now:</summary>
  
```
advancements-enlarger-0.2.2.jar
appleskin-mc1.16-fabric-1.0.11.jar
Autofish-0.8.6-fabric-mc1.16.jar
fabric-api-0.15.0+build.379-1.16.1.jar
hwyla-addon-horseinfo-0.2.1-1.16.1.jar
Hwyla-fabric-1.16.1-1.9.22-75.jar
inventoryprofiles-fabric-1.16.1-0.4.2.jar
leaf-decay-1.2.0-1.16.1.jar
lithium-fabric-mc1.16.1-0.5.1.jar
open2lan-0.0.1.jar
phosphor-fabric-mc1.16.1-0.6.0+build.7.jar
RoughlyEnoughItems-4.10.2.jar
sit-1.16.1-7_fabric.jar
sodium-fabric-mc1.16.1-0.1.0.jar
Xaeros_Minimap_20.16.0.1_Fabric_1.16.1.jar
XaerosWorldMap_1.7.4_Fabric_1.16.1.jar
```
  
</details>

**Comment by Enderminer** [comment]
> > > > Why not forge?
> > > > There's a 1.16.1 forge version of Hwyla and it'd be easier to update considering bookshelf already has a 1.16.1 version.
> > > 
> > > 
> > > Because I'm using forge ^^ It's better that forge for my needs 😋
> > 
> > 
> > I don't think you understood what I was saying.
> > You said you wanted a 1.16 fabric version of WAWLA, I was asking why not use forge rather than fabric because it would be easier to update.
> > Apologies if I wasn't clear before.
> 
> Sorry I did a typo when writing... I meant to say that I'm NOT using forge haha, I use mods that require fabric so I can't use forge anymore. I think modding in minecraft becomes more and more complex every year.
> 
> Or I just don't know that fabric and forge can be installed on a same instance? If so please tell me! It will be really helpful.
> 
> [spoiler] Here is my list of mods I use now:

Most of your mods have forge versions anyways. It would be great to have both a forge and a fabric version but with bookshelf being forge only and the previous mod versions being forge I'd think it'd be easier to just make a forge version.

**Comment by Darkhax** [comment]
Given the recent transphobic incident on their Discord I am doubling down on my decision not to support the Fabric project. I am not ruling out future community forks though.
