### ISSUE TITLE
Crash [WAWLA-1.16.4-7.0.1]

### ISSUE THREAD

**Issue by vertex101** [Darkhax-Minecraft/WAWLA#134]
when i have it in my client and try start i get this https://i.imgur.com/E3L3FSV.png

here is the full crash log

https://mcpaste.io/b58743bcac867d85

**Comment by Darkhax** [comment]
You also need Hwyla, it's listed as a dependency on the project page. You should be able to use the 1.16.2 version fine on 1.16.4. https://www.curseforge.com/minecraft/mc-mods/hwyla/files/3033593
