### ISSUE TITLE
Error when starting up server [1.16.4-7.0.1]

### ISSUE THREAD

**Issue by kyuu81** [Darkhax-Minecraft/WAWLA#135]
Received this error message when starting up server.

Details:
        Mod File: WAWLA-1.16.4-7.0.1.jar
        Failure message: Mod wawla requires minecraft 1.16.3
                Currently, minecraft is 1.16.4
        Mod Version: 7.0.1
        Mod Issue URL: https://github.com/Darkhax-Minecraft/Wawla/issues
        Exception message: MISSING EXCEPTION MESSAGE

but on the website, it said it was version 1.16.4.

**Comment by Darkhax** [comment]
Thank you for reporting. This issue should be fixed now.

**Comment by theoretischer** [comment]
No, it isn't
