### ISSUE TITLE
Wawla not working in Foamy Sands whenever there's a planted seaweed

### ISSUE THREAD

**Issue by diogoalexsmachado** [Darkhax-Minecraft/WAWLA#136]
How to replicate:

Load a Tropicraft Dimension, place Foamy Sands, plant seaweed. 

Wawla no longer shows up for that block.

Version: Wawla-1.12.2-2.6.275

![unknown (1)](https://user-images.githubusercontent.com/16367903/103281820-d4a98400-49cb-11eb-8714-8eba5aea8ca1.png)

**Comment by Darkhax** [comment]
I think you're looking for Hwyla. This mod does not control the tooltip.
