### ISSUE TITLE
Curse keeps installing the fabric version? + one more issue.

### ISSUE THREAD

**Issue by miraclematters** [Darkhax-Minecraft/WAWLA#139]
So curse keeps installing the fabric version of the mod alongside the forge version, i don't know if that's a mistake that you should be made aware of or not.

On another note, When I only install the forge version via the version select, it doesn't show anything in game even though it's installed. Are there settings i'm missing?

**Comment by Darkhax** [comment]
There is no fabric version of this mod. You're probably installing the fabric version of HWYLA which is the mod that adds the hud. This mod does not add a hud it just adds information to theirs. I plan to move away from HWLA late 1.16.4 or early 1.17.x.
