### ISSUE TITLE
Wawla not showing up

### ISSUE THREAD

**Issue by RegularKitsune** [Darkhax-Minecraft/WAWLA#140]
The hotkey for the config ingame works but when I look at a block nothing plops up. i don't know hot to write an issue post like this so if you need logs or anything I can upload them. i tried pressing the key to toggle wawla and the sneaking info both on and off nothing works.

**Comment by Darkhax** [comment]
This mod just adds more info to the tooltip, it has nothing to do with presenting the tooltip. You're looking for HWYLA.
