### ISSUE TITLE
Server does not start crash error says it needs WAILA

### ISSUE THREAD

**Issue by LuigiTP** [Darkhax-Minecraft/WAWLA#142]
this is the first part of the error message
-- MOD wawla --
Details:
        Mod File: WAWLA-1.16.5-8.0.1.jar
        Failure message: Mod wawla requires waila 0 or above
                Currently, waila is not installed
        Mod Version: 8.0.1
on the curse forge it said it didnt need waila so confused

**Comment by Darkhax** [comment]
The dependencies are clearly listed on CurseForge. You don't have Hwyla installed. Hwyla's mod ID is waila. If you do have Hwyla, you probably downloaded the Fabric version which will not work for Forge. The latest Forge version will work on 1.16.5 even though it says it hasn't been updated.
