### ISSUE TITLE
Repost to a chinese site

### ISSUE THREAD

**Issue by qwq233** [Darkhax-Minecraft/WAWLA#144]
hey there.
so there is 2 chinese sites called [mcmod](https://www.mcmod.cn) and [mcbbs](https://www.mcbbs.net) and i wanna repost your mod to this.can you give me the permission to do this. 
Thanks!

**Comment by Darkhax** [comment]
Hello, 

I am not interested in granting anyone special permissions to rehost my work beyond those given through the license.
