### ISSUE TITLE
Add license to Github and CurseForge

### ISSUE THREAD

**Issue by MoleMad** [Darkhax-Minecraft/WAWLA#145]
I'm not sure if this was a mistake on your part or intentional, but I noticed this mod doesn't have a license attached to it compared to other mods you have posted on GitHub and CurseForge. I think it would be very beneficial for mod users and developers if you outlined a license for this mod.

**Comment by funnykeyboardsymbols** [comment]
Bumping to show support for this issue, as I'm here specifically for the license in regards to distribution of the mod.

**Comment by Darkhax** [comment]
This is an older mod of mine that predates my move to open source. Moving forward it's safe to assume the code is LGPL 2.1.
