### ISSUE TITLE
Does not render properly with ViveCraft

### ISSUE THREAD

**Issue by slidedrum** [Darkhax-Minecraft/WAWLA#146]
I am trying to use this mod with the VR mod ViveCraft.  The mod moves all on screen HUD to your arm.  However this mod still renders on the mirror view, and is not visible in VR at all.  It also displays the block that your head is looking at, not the block you are about to mine (how it used to work in 1.12.2).  I tired asking around in the ViveCraft discord, but it is now my understanding that there is not much they can do, and changes would need to happen on WAWLA's end.  Thank you!

Using:
 - Minecraft 1.16.5
 - WAWLA-1.16.5-8.0.1.jar
 - Hwyla-forge-1.10.11-B78_1.16.2.jar
 - Bookshelf-1.16.5-10.0.7.jar
 - vivecraft-1.16.5-jrbudda-7-4-installer.exe
 - Forve V1.16.5 - 36.1.16

![](https://cdn.discordapp.com/attachments/194213677560365056/839338625786839070/unknown.png)

**Comment by Darkhax** [comment]
Hello, 

I believe you're meaning to post this on the Hwyla issue tracker. At this time WAWLA is just an addon for Hwyla which adds a lot of additional information. This will be changing in 1.17+ as Hwyla isn't really being maintained anymore.
