### ISSUE TITLE
Curse launcher can no longer install the mod due to required depedency.

### ISSUE THREAD

**Issue by uncertainluei** [Darkhax-Minecraft/WAWLA#152]
Due to the CurseForge Launcher's new update that adds built-in Fabric support and HWYLA being tagged as Fabric, people are unable to install the mod via the Curse Launcher (for Forge) as it cannot install the dependency, leading to an "Object reference not set to an instance of an object" error.

![image](https://user-images.githubusercontent.com/73312995/121882935-12476280-cd09-11eb-9c2a-c896e60acb60.png)

~~If update your required dependencies to use either [Jade](https://www.curseforge.com/minecraft/mc-mods/jade) or [WTHIT](https://www.curseforge.com/minecraft/mc-mods/wthit-forge) than HWYLA, it would be highly appreciated.~~

**Comment by Darkhax** [comment]
I've reached out to the CurseForge team and the Hwyla dev about this issue. I have no plans to support or endorse Jade or WTHIT.
