### ISSUE TITLE
Unnecessary dependency on Bookshelf?

### ISSUE THREAD

**Issue by ThexXTURBOXx** [Darkhax-Minecraft/WAWLA#155]
I am unsure about this "issue", but I am reporting it anyways...

After trying to start Minecraft with WAWLA and Bookshelf installed, I noticed that my friends who don't have Bookshelf installed can't play via LAN on my world anymore due to some registry entries missing on their end.
Then, I decided to try my "modpack" (which consists of just convenience mods that are only required on one end) with Bookshelf disabled but WAWLA still enabled and it loaded just fine and they could enter my world again.
Since Bookshelf is listed as a _required_ dependency, I thought something must have been broken here and, thus, I decided to try to compile WAWLA without Bookshelf in its classpath and even this worked without any issues.

I am leaving this issue here for further investigation if Bookshelf is still needed in order for WAWLA to still work. I didn't notice any issues yet in standard survival play (neither with the CurseForge version 8.0.6, nor with my own compiled version).

Edit: Tested using Minecraft 1.16.5

**Comment by Darkhax** [comment]
Only some versions of the mod require Bookshelf and it changes as I add/remove features from the base mod. If your setup is working without Bookshelf installed then it's probably fine to not include it in your pack/server.
