### ISSUE TITLE
Just a quick one and more of a question 

### ISSUE THREAD

**Issue by GMarty93** [Darkhax-Minecraft/WAWLA#157]
A lot of other mods add mimics as a mob that looks like a chest but WAWLA spoils the surprise. Is it at all possible to configure WAWLA to not display anything for certain tags? E.g. could it be possible to turn off WAWLA for chests

**Comment by Darkhax** [comment]
I suspect you have the wrong mod. At this time WAWLA is an addon for Hwyla/Waila and only runs on 1.12.2. WAWLA does not control the HUD being displayed, and tags do not exist on this version.

As for your question, these "Information Display HUD" mods usually provide an API that allows the mod author to change how something is displayed. They will often do this already for silverfish stone and the vanilla trapped chest. It is usually left up to the mod author adding the mimic block/entity to implement this for their own content.
