### ISSUE TITLE
issue? My  favorite tool is not availible  for 1.19+

### ISSUE THREAD

**Issue by s4sutler100** [Darkhax-Minecraft/WAWLA#160]
Wawla - What Are We Looking At  is not availible for 19.+. Are there plans to update?

**Comment by Darkhax** [comment]
Hello, I am planning to update WAWLA eventually however a lot has changed since this was last updated. Many of the mods this mod depends on such as WAILA or Hwyla post 1.7.10 are no longer being maintained. Unfortunately I do not have an ETA or a roadmap for when this will be updated.

**Comment by s4sutler100** [comment]
Understood though sad.
