### ISSUE TITLE
[1.12.2] WailaErrorOutput.txt showing errors with wawla?

### ISSUE THREAD

**Issue by InuYasha86000** [Darkhax-Minecraft/WAWLA#161]
I have a file with about 12 errors that start with: class net.darkhax.wawla.engine.waila.EntityProvider, i'm not sure which mod specifically it's pointing to but wawla is mentioned in the opening line.
[WailaErrorOutput.txt](https://github.com/Darkhax-Minecraft/WAWLA/files/11550358/WailaErrorOutput.txt)

**Comment by Darkhax** [comment]
This issue is caused by looking at an entity that has not been properly registered with the game. 1.12.2 is no longer supported or receiving updates, but you can disable the `debugEntities` option in the config to disable this code.
