### ISSUE TITLE
[FEEDBACK] Make monster eggs show up as different to their stone counterparts

### ISSUE THREAD

**Issue by chassinat0r** [Darkhax-Minecraft/WAWLA#162]
### Minecraft Version

1.12.2

### Mod Loader

Forge

### Feedback

I'm using this mod along with Biomes O' Plenty in 1.12.2 and there a lot of mountainous biomes added that I'm not certain whether monster eggs (infested stone blocks) generate naturally. I want to avoid mining the infested stone, however when I tested placing an infested stone block in creative and hovering over it, it simply showed stone. This is despite if I press FN+F3 Minecraft is clearly able to tell it is a "minecraft:monster_egg".

![2024-03-27_08 26 24](https://github.com/Darkhax-Minecraft/WAWLA/assets/123321721/c0c349ac-7ddd-474c-95ea-682c51a8e297)

I'm assuming your mod determines the block in question by the variant as the variant still shows as stone. I'm not sure if showing infested blocks as stone is intended behaviour, however whether it's infested or not can be determined simply by pressing FN+F3 and looking to the right to see the block.

I think it would be good if the mod somehow distinguishes infested stone from regular, non-infested stone. Maybe you could put (Infested) next to the type of stone in the popup if it's infested?

The rest of the mod is great, I really like it so far.

**Comment by Darkhax** [comment]
Hello, this is a feature added by Hwyla so you will need to disable it in their config. The feature was added because you're not meant to be able to tell that stone has silverfish or not. This mod has a similar feature for trapped chests that you can also disable if you want.
