### ISSUE TITLE
[BUG] WAWLA causes singleplayer server to crash when using any other terrain generation other than the default one

### ISSUE THREAD

**Issue by HauberDevs** [Darkhax-Minecraft/WAWLA#163]
### Minecraft Version

1.12.2

### Mod Version

2.6.275

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

So recently I tried to make a new world using Biomes O'Plenty as the terrain generation. It does generate the terrain, however I am just stuck on the loading screen, after checking if this maybe isnt an issue related to the world name, I concluded this was probaly an issue with WAWLA. After closing the game and deleting the mod, the world generated just fine.

What I would also like to mention is that this issue does not seem to occur if the normal generation is being used.

Here is the log file of this:
https://pastebin.com/KgqnrsY5

**Comment by Darkhax** [comment]
> I concluded this was probaly an issue with WAWLA.

What lead you to this conclusion? Wawla doesn't have any features related to world gen and the log file shows xaero minimap crashing.
