### ISSUE TITLE
Crash with Wawla in AE network

### ISSUE THREAD

**Issue by Keridos** [Darkhax-Minecraft/WAWLA#27]
Watching some items in an AE network leads to this crash when Wawla is installed: https://paste.ee/p/YfmKG

**Comment by darkhax** [comment]
Interesting issue, it looks like there is an issue with the block being rendered twice when it shouldn't be. Can you confirm that this issue only takes place when Wawla is installed? Looking at the crash it seems to be more of a Waila and AE problem.

**Comment by Keridos** [comment]
Funny is that removing Wawla made the crash disappear, but after another restart they happened again. Minecraft mod bugs at their finest again.
