### ISSUE TITLE
Looking at a filler will kill a server with WAWLA installed.

### ISSUE THREAD

**Issue by psychofad** [Darkhax-Minecraft/WAWLA#29]
When installing WAWLA on the client and server and then looking at a filler that is in operation the server will grind to a halt and become overloaded until you look away for a minute or so.  I wrongly assumed that this was a buildcraft issue, but after removing WAWLA on a hunch the server is unaffected when I look at a filler.   There are no crash logs as this does not crash the server it simply overloads it (TPS = 0.01) so unfortunately I have nothing to post with this issue.  I did test looking at a filler after placing it and this will not trigger the issue.  The filler must be operational (tested with clearing land) for this to occur.  

Steps to reproduce.
1. run a server and client with at least buildcraft, waila and wawla installed
2. use markers to mark out a 64x64x64 area to clear (tested clearing mostly stone)
3. place filler down and set to clear area
4. Supply power to filler.
5. look directly at the filler block as the red cubes are flowing out of it
6. check server tps

**Comment by asiekierka** [comment]
What are we looking at here? Probably a case of syncing the entire NBT tag, which for BC fillers can easily go into a megabyte or two.

**Comment by darkhax** [comment]
As @asiekierka suggested, this is likely an issue with NBT being sent to the client from the server. Waila will sync the entire nbt of any tile or entity when looked at, this is so all information displayed is accurate. Within Waila, you register the blocks that you want to cause the sync of nbt data, and then that block and all blocks which extend from that block will also be synced using packets. Unfortunately my mod Wawla has a lot of general features that do not pertain to just one block, such as light level, so I register all blocks by default.Fortunately, I don't make use of the generalized nbt syncing right now, so I should be able to remove it.

**Comment by psychofad** [comment]
Thanks for looking into this...sounds like you know how to fix it.  I have removed the mod for now...and wow...while I was typing you seemed to have done the fix.  :D 

Thanks

**Comment by darkhax** [comment]
Yeah, no problem.

I prefer to only push larger builds, so this change isn't included in any of the downloads on my pages (yet), however given the nature of this issue, I would assume you and your players will want to use the latest change as soon as possible. Here is a build containing this patch for you, feel free to use it yourself, put it on your server, or use in a modpack. [Download Link](https://dl.dropboxusercontent.com/u/38575752/files/Wawla-1.7.10-1.1.2-pre1.jar)
