### ISSUE TITLE
wawla.showHat option can grind server to a crawl when players draw near

### ISSUE THREAD

**Issue by rickybrent** [Darkhax-Minecraft/WAWLA#30]
This may have to do with other mods installed, but while using iChun's hat and hatstand mods on client and server, and wawla, the server lags and misses ticks whenever two players look at each other if one's wawla.showHat option is set to true. (Also, no hat name appears, but that's less of a big deal to us.)

Setting the first wawla.showHat to false and the second wawla.showHat to true in the server's Waila.cfg file (to disable showing hat names and force clients to honor this) works around the issue -- and lets us keep using this amazing mod. :) Thanks!

**Comment by darkhax** [comment]
Interesting issue, I will look into it, thanks for bringing it up.

**Comment by darkhax** [comment]
Feature has been removed until further notice. Re-implementation planned for next version.
