### ISSUE TITLE
Not really a problem, but...

### ISSUE THREAD

**Issue by koalalord9999** [Darkhax-Minecraft/WAWLA#33]
I know it says Wawla is a client side mod... But does a Pixelmon server have to have Wawla before client side users can see the additional information on the pixelmon; like size and held items?
Currently, I'm using the 1.2.0 version of Wawla and my server only has pixelmon and 1 other mod. I only see if they are sitting or not. :(

If you know the answer to this, that would be great! thanks in advance :)

**Comment by darkhax** [comment]
Hey there, Wawla and Waila are not a client side mods, they has very important code which is handled on both the client and the server. These mods only have access to the data which mods generate, this data is usually only available on the server, however occasionally some data will be available on the client (stuff that is used for rendering mostly). I would suggest that you update to Wawla 1.2.1 and then try again. If it does not work, try sneaking while looking at a pixelmon. If neither of those work, then the data you are trying to get is not available on the client side, and you will have to install the mod(s) on your server.

**Comment by koalalord9999** [comment]
Alright, thanks, I'll try that :)

**Comment by darkhax** [comment]
Awesome :)
