### ISSUE TITLE
[Suggestion] Additional block data

### ISSUE THREAD

**Issue by esotericist** [Darkhax-Minecraft/WAWLA#34]
It would be really helpful for some things I'm doing if WAWLA had some optional settings for showing hardness and blast resistance in the tooltip.

To my dismay, I haven't been able to find any kind of tool for querying this information, and it seemed like WAWLA was the best fit given it already does harvestability information.

**Comment by darkhax** [comment]
Sounds like a great idea, however it may be a bit annoying to have enabled by default. The option will be disabled by default, but it should be very easy for you to configure it.

**Comment by esotericist** [comment]
Yeah, I assumed disabled by default... This is basically a content creator/debugging feature, most people won't need it

**Comment by darkhax** [comment]
The new build has been submitted for approval. It will be available [here](http://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at/files/2267304) once it is approved.
