### ISSUE TITLE
Add support for the RFTools villager

### ISSUE THREAD

**Issue by KnightMiner** [Darkhax-Minecraft/WAWLA#35]
Can you add support for the [RFTools](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2229562-rftools-dimension-builder-teleportation-crafter) villager in the list of professions in the .lang file? It uses the ID `description.villager.profession.rftools.rftoolsvillager` in game, and as far as I can tell, its profession name is simply "RFTools", as the only reference to its name is in the config file where is simply calls it the RFTools villager.

**Comment by darkhax** [comment]
Thank you for reporting this. I will add it right now.
