### ISSUE TITLE
Crash While Looking at Slabs

### ISSUE THREAD

**Issue by Darkosto** [Darkhax-Minecraft/WAWLA#38]
Hey Darkhax,

I'm getting a crash when looking at a top-half wooden slab from underneath the block:

http://pastebin.com/w2nyJBpg
http://pastebin.com/B46rNany

I'm using MC 1.9 Forge 1858 and version 2.2.0.179

Thanks for taking a look into this :)
Darkosto

**Comment by darkhax** [comment]
Thank you for reporting this issue. I was not able to reproduce your crash, however I did notice some related code which had a mistake in it, which is highly likely to be the cause of the crash. A new build has been uploaded to CurseForge, you can find it [here](http://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at/files/2293041). Let me know if this fixed it for you. If not, please post the new crash log.

**Comment by darkhax** [comment]
Closing because it got stale.
