### ISSUE TITLE
Feature Request: Storage Drawers Compatability

### ISSUE THREAD

**Issue by Nogal** [Darkhax-Minecraft/WAWLA#42]
I was wondering if you would be interested in adding support to display the items and  stack count of the items stored within the "Storage Drawers" mod. It's a nifty mod that I include in most of my packs that has replaced barrels for most of my playthroughs, however in newer builds (anything beyond 1.7.10) there are no plugins for WAILA which support it.

http://minecraft.curseforge.com/projects/storage-drawers?gameCategorySlug=mc-mods&projectID=223852

**Comment by darkhax** [comment]
Huh, I was under the impression that that mod had their own plugin built in. I will look into it and give you more info after that.

**Comment by NovaViper** [comment]
@Nogal Hey. Storage Drawers just released an [update](https://minecraft.curseforge.com/projects/storage-drawers/files/2405130) that fixed the compatibility with HYWALA
