### ISSUE TITLE
WAWLA not Displaying information when WAILA is present

### ISSUE THREAD

**Issue by smithnc07** [Darkhax-Minecraft/WAWLA#43]
System: Mac OS X 10.11.5
Java Version: 8r74
WAWLA Version: Wawla-1.9.4-2.2.1.188
WAILA Version: Waila-1.7.0-B3_1.9.4
Forge Version: Forge 1.9.4-12.17.0.1937

When Info Engine is loaded as Waila nothing is being added to the WAILA hud. 
If I remove WAILA, WAWLA properly switches to Info Engine ICSE and displays the proper additional information. 

As far as I know there are no errors when starting up.  Attached is a screen shot of the F3 Debug showing that it has loaded WAILA as the Info Mod, but nothing is being added to the Hud for the burning Furnace. 

![debugscreen](https://cloud.githubusercontent.com/assets/1372154/15688889/026485e0-2742-11e6-9ca4-96815a14416c.png)

**Comment by darkhax** [comment]
Thank you for reporting this issue, I thought I already fixed this, but it looks like the fix was undone. A new version will be up on CurseForge soon.

**Comment by smithnc07** [comment]
Awesome, Thank you. We appreciate all the time you have spend on providing us with great mods.
