### ISSUE TITLE
[Server Startup Crash] WAWLA causing a crash on server startup.

### ISSUE THREAD

**Issue by Kris1432** [Darkhax-Minecraft/WAWLA#44]
MC Version: 1.9.4
Mod Version: Wawla-1.9.4-2.2.1.189
Cause: Startup on a server
Log: http://pastebin.com/TTHWn5Zv

**Comment by darkhax** [comment]
Thank you for reporting this. I have fixed it and it will be available in the next update. Waiting on CurseForge to approve it.

**Comment by Kris1432** [comment]
No worries :) jusr here to help!
