### ISSUE TITLE
Issue with your mod and mine

### ISSUE THREAD

**Issue by RedBullSlurpie** [Darkhax-Minecraft/WAWLA#45]
So, when using WAWLA, when i look at my Nether Lapis Ore.. it displays a purple/black texture, otherwise no texture.. If i don't use WAWLA, it shows up fine, the texture in the WAILA tooltip. I also use Harvestability. Once I add your mod, WAWLA it shows up with no texture. It ONLY seems to happen with my Nether Lapis Ore, everything else seems fine. There is no crash log, or crash, but i will provide a screen shot too both it working, and not working so you can see the difference. Thanks.

http://imgur.com/a/XpndR

**Comment by darkhax** [comment]
Is there anything special with your block that may be causing this issue? Wawla should not be messing with that in any way. Could I get a log along with mc version numbers and mod version numbers?

**Comment by RedBullSlurpie** [comment]
Nope, I don't seem to have anything special in my mod block class. I've written all my blocks the same. It only seems to happen with Lapis though which i find very weird, since all my blocks are written the same, if it was an issue with your mod, which it seems to be pointing that way, then why wouldn't it do it for all others in my mod? Makes no sense. Anyway, sure ill get you that log. I'm not sure which log it is, so ill post a few. By the way my mod's name is Slurpie's Dongles if you wanted to look at it for yourself.

I can also confirm when creating my mod in Intellijay and testing it, I've added Waila, WAWLA, and Harvestability to the mods folder when building my mod, and with those 3, and my mod it still has the issue, once removing WAWLA, it worked fine. 

Log 1- http://pastebin.com/7jt3De2m

Log 2- http://pastebin.com/RBch4YMS

Log 3- http://pastebin.com/huMFrHau

Mod list- http://pastebin.com/x6s8PcdT

Mc version- 1.9.4

Forge version 1939

**Comment by darkhax** [comment]
The issue is related to how your block handles the drops. I believe it was showing your ore with the meta value of the lapis drop. I switched the way Wawla handles stacks to account for this.
