### ISSUE TITLE
[1.9.4] Format Error in tooltips.

### ISSUE THREAD

**Issue by Laruae** [Darkhax-Minecraft/WAWLA#48]
Seeing a format error in the tooltip for the Enchanted Books.

Screenshot of tooltip w/o shift.
![](http://i.imgur.com/I8GNwUO.png)

Screenshot of tooptip w/ shift.
![](http://i.imgur.com/wrTjuYZ.png)

It does say that the format error is being added by Minecraft.

**Comment by darkhax** [comment]
Thank you for reporting this issue. The Format error bit is not part of the "Added by Minecraft" text line.

**Comment by darkhax** [comment]
This issue should be fixed in the latest build. If it is not, let me know and I will fix it again.
