### ISSUE TITLE
Curseforge release tagging

### ISSUE THREAD

**Issue by jriwanek** [Darkhax-Minecraft/WAWLA#50]
Wawla-1.10.2-2.3.0.196.jar on CF is tagged as compatible with 1.9.4, but will cause a message about ICSE needing 1.10.2.

**Comment by darkhax** [comment]
Thank you for the report, that build was missing a commit. Fixed in https://github.com/Darkhax-Minecraft/WAWLA/commit/f0dd878fee9cdd7c90d91eb1da78eb4b343205d6
