### ISSUE TITLE
1.10.2 Client Crashed with Wawla-1.10.2-2.3.0.206.jar

### ISSUE THREAD

**Issue by 7934345** [Darkhax-Minecraft/WAWLA#55]
Game Version 1.10.2
Forge is latest

java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting

after remove the wawla, everything goes well.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingPlugin (JustEnoughCharacters-1.10.2-0.0.1.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 9/27/16 4:42 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
	at net.darkhax.icse.client.render.RenderingHandler.onOverlayRendered(RenderingHandler.java:122)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_118_RenderingHandler_onOverlayRendered_Text.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:694)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:171)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1369)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.mojang.realmsclient.gui.ChatFormatting
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.darkhax.icse.client.render.RenderingHandler.onOverlayRendered(RenderingHandler.java:122)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_118_RenderingHandler_onOverlayRendered_Text.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:694)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:171)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['wtf'/2245, l='MpServer', x=-189.50, y=84.00, z=48.50]]
	Chunk stats: MultiplayerChunkCache: 525, 525
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-183,64,54), Chunk: (at 9,4,6 in -12,3; contains blocks -192,0,48 to -177,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 91 game time, 91 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 75 total; [EntityBat['蝙蝠'/2433, l='MpServer', x=-170.69, y=32.14, z=125.52], EntitySquid['鱿鱼'/2306, l='MpServer', x=-192.33, y=51.53, z=-14.74], EntityBat['蝙蝠'/2434, l='MpServer', x=-166.25, y=32.36, z=127.50], EntitySquid['鱿鱼'/2307, l='MpServer', x=-189.14, y=52.31, z=-11.88], EntitySquid['鱿鱼'/2309, l='MpServer', x=-186.54, y=51.74, z=-13.40], EntityBat['蝙蝠'/2565, l='MpServer', x=-240.28, y=27.00, z=127.11], EntitySquid['鱿鱼'/2318, l='MpServer', x=-191.50, y=57.12, z=3.90], EntitySquid['鱿鱼'/2319, l='MpServer', x=-194.24, y=54.62, z=2.69], EntitySquid['鱿鱼'/2320, l='MpServer', x=-197.10, y=55.25, z=2.59], EntitySquid['鱿鱼'/2322, l='MpServer', x=-221.64, y=61.00, z=3.09], EntitySquid['鱿鱼'/2323, l='MpServer', x=-222.09, y=62.50, z=3.52], EntitySquid['鱿鱼'/2324, l='MpServer', x=-217.04, y=62.41, z=-1.98], EntityBabySquid['Baby Squid'/2326, l='MpServer', x=-137.06, y=52.71, z=112.02], EntityBabySquid['Baby Squid'/2327, l='MpServer', x=-130.78, y=55.22, z=113.53], EntityBabySquid['Baby Squid'/2330, l='MpServer', x=-222.77, y=62.04, z=2.53], EntityWitch['女巫'/2461, l='MpServer', x=-185.50, y=18.00, z=123.50], EntityBat['蝙蝠'/2465, l='MpServer', x=-189.81, y=31.76, z=105.47], EntityBat['蝙蝠'/2466, l='MpServer', x=-194.71, y=31.49, z=104.37], EntityBat['蝙蝠'/2355, l='MpServer', x=-147.03, y=48.70, z=-29.75], EntityPig['猪'/53, l='MpServer', x=-265.50, y=78.00, z=57.50], EntityPig['猪'/54, l='MpServer', x=-265.50, y=80.00, z=60.50], EntityPig['猪'/55, l='MpServer', x=-265.50, y=79.00, z=58.50], EntityPig['猪'/56, l='MpServer', x=-265.50, y=80.00, z=60.50], EntitySheep['羊'/57, l='MpServer', x=-251.50, y=93.00, z=20.50], EntitySheep['羊'/58, l='MpServer', x=-248.50, y=94.00, z=18.50], EntitySheep['羊'/59, l='MpServer', x=-253.50, y=93.00, z=18.50], EntitySheep['羊'/60, l='MpServer', x=-255.50, y=93.00, z=18.50], EntityPig['猪'/61, l='MpServer', x=-238.50, y=85.00, z=31.50], EntityItem['item.tile.gravel'/2237, l='MpServer', x=-251.88, y=37.00, z=72.27], EntityPig['猪'/62, l='MpServer', x=-237.50, y=90.00, z=27.50], EntityPig['猪'/63, l='MpServer', x=-234.55, y=90.00, z=26.50], EntityItem['item.tile.gravel'/2239, l='MpServer', x=-250.98, y=37.00, z=72.64], EntityPig['猪'/64, l='MpServer', x=-233.66, y=90.00, z=26.50], EntityPig['猪'/65, l='MpServer', x=-225.50, y=85.00, z=42.50], EntityPig['猪'/66, l='MpServer', x=-225.50, y=85.00, z=42.50], EntityPig['猪'/67, l='MpServer', x=-227.45, y=81.00, z=41.24], EntityPig['猪'/68, l='MpServer', x=-227.50, y=85.00, z=45.50], EntityFallingBlock['下落的方块'/1733, l='MpServer', x=-342.50, y=25.49, z=152.50], EntityPig['猪'/69, l='MpServer', x=-190.50, y=83.00, z=45.50], EntityBabyZombie['僵尸'/2757, l='MpServer', x=-236.50, y=34.45, z=98.40], EntityPlayerSP['wtf'/2245, l='MpServer', x=-189.50, y=84.00, z=48.50], EntityPig['猪'/70, l='MpServer', x=-189.50, y=84.00, z=46.50], EntityZombieChicken['Zombie Chicken'/2758, l='MpServer', x=-236.50, y=34.00, z=98.50], EntityPig['猪'/71, l='MpServer', x=-188.50, y=84.00, z=44.50], EntityPig['猪'/72, l='MpServer', x=-188.50, y=84.00, z=43.50], EntityPig['猪'/73, l='MpServer', x=-176.60, y=73.69, z=64.61], EntityPig['猪'/74, l='MpServer', x=-177.50, y=81.00, z=58.50], EntityPig['猪'/75, l='MpServer', x=-176.50, y=87.00, z=55.30], EntityPig['猪'/76, l='MpServer', x=-174.50, y=83.00, z=58.50], EntityPig['猪'/78, l='MpServer', x=-163.50, y=79.00, z=5.50], EntityCreeper['爬行者'/2638, l='MpServer', x=-228.50, y=18.00, z=111.50], EntityPig['猪'/79, l='MpServer', x=-162.50, y=78.00, z=1.50], EntityPig['猪'/80, l='MpServer', x=-164.57, y=79.00, z=6.21], EntityZombie['僵尸'/2640, l='MpServer', x=-226.50, y=18.00, z=109.50], EntityPig['猪'/81, l='MpServer', x=-163.50, y=79.00, z=5.50], EntitySpider['蜘蛛'/2641, l='MpServer', x=-229.50, y=18.00, z=111.50], EntityPig['猪'/82, l='MpServer', x=-168.57, y=90.00, z=39.48], EntityPig['猪'/83, l='MpServer', x=-165.01, y=91.00, z=40.50], EntityPig['猪'/84, l='MpServer', x=-158.68, y=92.00, z=41.56], EntityPig['猪'/85, l='MpServer', x=-163.50, y=92.00, z=46.50], EntityCreeper['爬行者'/2389, l='MpServer', x=-190.50, y=15.00, z=85.50], EntityPig['猪'/86, l='MpServer', x=-140.50, y=88.00, z=19.50], EntityPig['猪'/87, l='MpServer', x=-140.50, y=88.00, z=19.50], EntitySkeleton['骷髅'/2647, l='MpServer', x=-110.50, y=41.00, z=57.50], EntityPig['猪'/88, l='MpServer', x=-139.50, y=87.00, z=21.50], EntityPig['猪'/89, l='MpServer', x=-136.50, y=85.00, z=20.50], EntitySkeleton['骷髅'/2649, l='MpServer', x=-183.50, y=16.00, z=128.50], EntitySkeleton['骷髅'/2650, l='MpServer', x=-185.50, y=16.00, z=127.50], EntityBabyCreeper['Baby Creeper'/2651, l='MpServer', x=-230.50, y=18.00, z=112.50], EntityZombie['entity.Zombie.name'/2675, l='MpServer', x=-228.50, y=18.00, z=110.50], EntityZombie['entity.Zombie.name'/2676, l='MpServer', x=-227.50, y=18.00, z=111.50], EntityBat['蝙蝠'/2297, l='MpServer', x=-122.04, y=22.07, z=39.55], EntitySquid['鱿鱼'/2302, l='MpServer', x=-130.31, y=54.25, z=104.60], EntitySquid['鱿鱼'/2303, l='MpServer', x=-136.41, y=53.65, z=110.77], EntityBat['蝙蝠'/2431, l='MpServer', x=-166.61, y=32.11, z=124.93]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7029233376 bytes (6703 MB) / 7927234560 bytes (7560 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8192m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.1.2088 Optifine OptiFine_1.10.2_HD_U_C3 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2088.jar) 
	UCHIJAAAA	Forge{12.18.1.2088} [Minecraft Forge] (forge-1.10.2-12.18.1.2088.jar) 
	UCHIJAAAA	je_characters{0.0.1} [Just Enough Characters] (minecraft.jar) 
	UCHIJAAAA	slimecompendium{1.4} [Slime Compendium] ([1.10.2]SlimeCompendium1.4.jar) 
	UCHIJAAAA	babymobs{1.5.1} [Baby Mobs] (BabyMobs-1.10.2-1.5.1.jar) 
	UCHIJAAAA	XaeroBetterPvP{1.10.8} [Better PVP Mod] (BetterPvP_1.10.8_Forge_1.10.2.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2085} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2085-universal.jar) 
	UCHIJAAAA	JEI{3.11.2.277} [Just Enough Items] (jei_1.10.2-3.11.2.277.jar) 
	UCHIJAAAA	blockdrops{1.0.11} [Block Drops] (BlockDrops-1.10.2-1.0.11.jar) 
	UCHIJAAAA	infinitylib{1.10.2-@MAJOR@.@MINOR@.@REVIS@} [InfinityLib] (infinityLib-0.1.jar) 
	UCHIJAAAA	boatifull{@MAJOR@.@MINOR@.@REVIS@} [Boatifull] (boatifull-0.1.jar) 
	UCHIJAAAA	chameleoncreepers{1.4.1} [Chameleon Creepers] (chameleoncreepers-1.4.1-1.10.2.jar) 
	UCHIJAAAA	ChestTransporter{2.5.2} [Chest Transporter] (ChestTransporter-1.10.2-2.5.2.jar) 
	UCHIJAAAA	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCHIJAAAA	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UCHIJAAAA	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.4-1.3.1.jar) 
	UCHIJAAAA	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJAAAA	glasscraftmod{1.0} [Glasscraft] (Glasscraftmod v1.0 - MC1.10.2 Forge.jar) 
	UCHIJAAAA	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCHIJAAAA	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	itemscroller{0.7.1} [Item Scroller] (itemscroller-1.10.2-0.7.1.jar) 
	UCHIJAAAA	jeresources{0.5.1.56} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.1.56.jar) 
	UCHIJAAAA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
	UCHIJAAAA	malisiscore{1.9.4-4.1.1} [MalisisCore] (malisiscore-1.9.4-4.1.1.jar) 
	UCHIJAAAA	malisisblocks{1.9.4-4.0.1} [Malisis Blocks] (malisisblocks-1.9.4-4.0.1.jar) 
	UCHIJAAAA	MoreFurnaces{1.8.2} [More Furnaces] (MoreFurnaces-1.10.2-1.8.2.jar) 
	UCHIJAAAA	progressiveautomation{1.6.51} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.51.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJAAAA	spawnercraft{3.1} [SpawnerCraft] (SpawnerCraft 1.10.2-3.2.0.jar) 
	UCHIJAAAA	StellarAPI{0.5.4.1.3} [Stellar API] (Stellar API-0.5.4.1.3.jar) 
	UCHIJAAAA	stellarsky{0.5.5.1.7} [Stellar Sky] (Stellar Sky-0.5.5.1.7.jar) 
	UCHIJAAAA	trashslot{6.3.6} [TrashSlot] (TrashSlot_1.10.2-6.3.6.jar) 
	UCHIJAAAA	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAA	waterstrainer{1.3.0} [Water Strainer] (WaterStrainer-1.9.4-1.3.0.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.206.jar) 
	UCHIJAAAA	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.206.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (JustEnoughCharacters-1.10.2-0.0.1.jar)
  towdium.je_characters.ClassTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.22' Renderer: 'GeForce GTX 780M/PCIe/SSE2'
	Launched Version: HMCL 2.5.3.88
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 780M/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.22, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Fanver_Modded_Universal.zip (incompatible), Soartex_Fanver.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C3
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 368.22
	OpenGlRenderer: GeForce GTX 780M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by darkhax** [comment]
This is a strange issue that I can not reproduce. Could you please try the latest version of Wawla and try again?

**Comment by 7934345** [comment]
I just reset my game and find everything goes well...

;( what a blablabla


Thanks for ur response :) nice mod.
