### ISSUE TITLE
[1.10.2] SMP Server Crash Loading WAWLA

### ISSUE THREAD

**Issue by Morpheus1101** [Darkhax-Minecraft/WAWLA#56]
Forge *.2094
WAWLA *.210
JAVA v8

Crash log @ http://pastebin.com/9AkUaPrh

**Comment by C0rn3j** [comment]
Same issue here.

**Comment by C0rn3j** [comment]
Seems to happen with version 209 too.

**Comment by darkhax** [comment]
Thanks for the report. Let me know if anything else happens.

**Comment by Morpheus1101** [comment]
You can count on me doing that :D
