### ISSUE TITLE
Waila compatability broken?

### ISSUE THREAD

**Issue by AlHollandiyah** [Darkhax-Minecraft/WAWLA#59]
When I had wawla without waila it sat in the top left corner, mixing with the text of in game info xml, thus rendering unreadable. Now there is a download for waila called Waila v1.7.0-B3 that is for 1.10.2 and works fine, but the extra info that I have wawla for is not showing anywhere. Not in the topleft corner, and not in the waila hud either. I have tried wawla 206 and 212 but neither makes a difference. The config has everything on default settings. What goes wrong here?

**Comment by darkhax** [comment]
Are you sure you have both mods installed? I have confirmed that the mod works as intended with [Waila 1.7.0-B3](https://minecraft.curseforge.com/projects/waila/files/2301859) and [WAWLA 2.3.1.212](https://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at/files/2336533).

**Comment by AlHollandiyah** [comment]
Yes I do.

**Comment by AlHollandiyah** [comment]
Here is my modlist. Before I added WAILA in Wawla was showing some info in the topleft corner but as you can see in the screenshots above that was also where In Game Info XML is positioned which made it unreadable. Then I entered Waila into the mix and the info in the topleft corner disappeared but it didn't reappear in the Waila HUD.

- Forge 12.18.2.2119
- Liteloader v1.10.2
- CodeChickenCore v2.3.5.91
- CodeChickenCore CodeChickenLib v2.4.3.130
- CodeChickenCore JEI v3.12.8.323
- CodeChickenCore NotEnoughItems v2.1.2.162
- InventoryTweaks v1.61-58
- LunatriusCore v1.1.2.36
- LunatriusCore InGameInfoXML v2.8.1.88
- LunatriusCore LaserLevel v2.1.0.15
- OptiFine vHD U C1
- VoxelMap v1.6.15
- Waila v1.7.0-B3
- Wawla v2.3.0.206
- Worldedit v6.1.4
- WorldEditCUI v1.10_00

**Comment by darkhax** [comment]
Okay, so as your screenshot showed, WAWLA is clearly working as intended. The breedable tooltip only shows if you are holding a breeding item for that animal.

**Comment by AlHollandiyah** [comment]
Well, it shows the "breeding" tag wheter I look at a sheep that just bred, or a lamb, or a 'fresh' sheep, so in fact it tells me nothing. It also supposes to tell the age of a young animal, and loads of other info that I don't get. This leads me to conclude that it actually doesn't work. Right now its 'waila plus an uninforming breeding tag'?

**Comment by darkhax** [comment]
As I said, the breeding tag is only for if the item you are holding is a valid breeding item for that animal. The breeding timer is handled separately. There seems to be a bug in Waila that prevents the timer from working on servers, nothing I can do about that. If you don't like the tag you can disable it in the configs.

**Comment by AlHollandiyah** [comment]
But apart from that tag, info about aging up, furnaces, armor points, etc,, block info, vanilla entity info and all the other stuff listed at the curse forge page don't show up either. So all I have is this 'breeding' tag that shows up on any single animal that can eat what I'm holding. That means something is going wrong, right?

**Comment by AlHollandiyah** [comment]
Ok, so I ran some other tests and there appears to be about half/half split of what works and what doesnt. Are there more info parts that you need to hold specific items or press a key for?

Generic Entity: Breeding/baby timers / tamed / sitting does NOT work, armor points does.
Generic Block Info: Blast resistence / hardness / harvestability does NOT work, enchant power / break percentage does.
Vanilla Entity Info: XP orb does NOT work, speed/jump of a horse / item frame / villager profession does.
Vanilla Block Info: Furnace info does NOT work, heads does.

**Comment by darkhax** [comment]
>Entity: Breeding/baby timers / tamed / sitting does NOT work, armor points does.
Tamed/Sitting requires that you own the mob. Anything related to entities might not work as expected on servers due to a bug in waila. 

>Block Info: Blast resistence / hardness / harvestability does NOT work, enchant power / break 
Blast resistance and hardness are disabled by default. Harvestability requires that you have the item in hand to mine the block. 

>Vanilla Entity Info: XP orb does NOT work, speed/jump of a horse / item frame / villager profession does.
XP orbs do not work with Waila as Waila does not support non living entities. It does work with ICSE. 

>Vanilla Block Info: Furnace info does NOT work, heads does.
Sneak while looking at the furnace

**Comment by AlHollandiyah** [comment]
Everything confirmed except furnaces, sneaking does not make a difference, it just shows nothing else but what Waila already does "Furnace / Minecraft".... Thanks for your extra information, that really helped.
