### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid (ExNihiloOmnia interraction)

### ISSUE THREAD

**Issue by kane-thornwyrd** [Darkhax-Minecraft/WAWLA#60]
Hello, thank you for your awesome mod.

Scenario:
Crash when hovering the witchwater bucket in the creative inventory.

[Logs](https://gist.github.com/kane-thornwyrd/cad4fc5309ab62ee7a7f8d0a1ab421e7)

Issue mirrored as https://github.com/Jozufozu/ExNihiloOmnia/issues/96

**Comment by kane-thornwyrd** [comment]
Also crash on Forge 12.18.2.2151

**Comment by darkhax** [comment]
I have determined that WAWLA is not in the wrong in this situation. The issue must be resolved on their end.

**Comment by kane-thornwyrd** [comment]
thanks
