### ISSUE TITLE
Feature Request [Re-Implantation if possible]: Pixelmon Mod Support

### ISSUE THREAD

**Issue by CyborgMarioMC** [Darkhax-Minecraft/WAWLA#61]
Hi, i used to use this mod when it had pixelmon supported as one of its supported mods but i was wondering if you could re-add that implantation to the mod... i miss that feature and it would be awesome to have it again. i remember the feature had this to be added to the config:

B:wawla.pixelmon.showAbility=true
B:wawla.pixelmon.showApricornGrowth=true
B:wawla.pixelmon.showApricornProduct=ture
B:wawla.pixelmon.showEV=true
B:wawla.pixelmon.showFriendship=true
B:wawla.pixelmon.showHeldItem=true
B:wawla.pixelmon.showIV=true
B:wawla.pixelmon.showNature=true
B:wawla.pixelmon.showSize=true
B:wawla.pixelmon.useSneak=true

i hope the pixelmon mod support gets re-added to this mod.

**Comment by darkhax** [comment]
Unfortunately I no longer have access to the Pixelmon Mod Source, so it is not easily possible to add support at this time. I am trying to add it back though.

**Comment by darkhax** [comment]
After looking into it further, the Pixelmon team is no longer willing to give me the same level of access, so I will not be continuing pixelmon support moving forward.

**Comment by selsphere** [comment]
Is there any reason why the pixelmon team dosent want to grant you access? I'd really like to see this feature re-added!
