### ISSUE TITLE
crash when looking at RS drives.

### ISSUE THREAD

**Issue by darkmdbeener** [Darkhax-Minecraft/WAWLA#62]
when looking at a Refined Storage drive on a server you will crash out.

1.10.2-2.3.1.214
Skyfactory 3.0.6 beta

https://u.nya.is/uldukh.log

**Comment by darkmdbeener** [comment]
maybe disregard this. i think it waila that might be the issue.

**Comment by TehNut** [comment]
This is an issue on my end. https://github.com/TehNut/HWYLA/issues/42
