### ISSUE TITLE
Error On Connect

### ISSUE THREAD

**Issue by JohnHollowell** [Darkhax-Minecraft/WAWLA#64]
On a Sky Factory 3 server I play on, I often am unable to connect due to this error.
Server log: https://gist.github.com/JohnHollowell/16f5dd0d79c3529bd338563976a3948d

Wawla-1.10.2-2.3.1.214 (other mods with versions can be seen on line 8 of the log)

**Comment by JohnHollowell** [comment]
It seems this may be caused by a large number of dimensional teleports (with dislocator from Draconic Evolution). The error often occurs on entering a dimension (whether teleport or login).

**Comment by darkhax** [comment]
You're looking for the [Hwyla](https://github.com/TehNut/HWYLA) mod. Wawla does not provide any Waila code.

**Comment by JohnHollowell** [comment]
Thanks!
