### ISSUE TITLE
Nothing shows on 1.11.2

### ISSUE THREAD

**Issue by NovaViper** [Darkhax-Minecraft/WAWLA#68]
Hey uh.. I just got the 1.11.2 Alpha and nothing literally shows up on the screen when I'm looking at something.

**Comment by darkhax** [comment]
Do you have Hwyla installed? The mod is no longer stand alone for 1.11.2.

**Comment by NovaViper** [comment]
Oh, no I didnt

**Comment by darkhax** [comment]
Okay, well install Hwyla and it will start working.

**Comment by NovaViper** [comment]
That fixed it, thanks!
