### ISSUE TITLE
Crash on Server Start up

### ISSUE THREAD

**Issue by BSKCorp** [Darkhax-Minecraft/WAWLA#71]
Forge 1.11.2-12.30.0.2282
WAWLA - 1.11.2-2.4.0.219

Crash Log - https://pastebin.com/bhPkreBk

**Comment by darkhax** [comment]
This issue was fixed in https://github.com/Darkhax-Minecraft/WAWLA/commit/624c7ecd76f095420da65de9859d14c654750164 Please try with 2.4.0.231
