### ISSUE TITLE
Won't display block info with original WAILA

### ISSUE THREAD

**Issue by NovaViper** [Darkhax-Minecraft/WAWLA#73]
Hey, ProfMobius just updated Waila and I notice that when I run both that and this mod together.. I don't get the block information that I used to get with Hywla (the forked version of Waila). However I still can't get information on entities

**Comment by darkhax** [comment]
In the 1.11.2 update I dropped support for Waila, because it wasn't updated yet. I will be re-adding support soon now that it's updated. That said, the Waila for 1.11.2 still has all of the bugs and I don't know if they will be fixed. I would highly recommend Hwyla.
