### ISSUE TITLE
Crash between Wawla, Hwyla and Timberjack 1.11.2

### ISSUE THREAD

**Issue by sweetsosweet** [Darkhax-Minecraft/WAWLA#77]
I'm not sure where the issue originates, but if I remove Wawla it doesn't happen any more.

Here's the crash report:

[paste](https://pastebin.com/LykcW742)

**Comment by darkhax** [comment]
The issue is in TimberJack, it's not expecting Waila/Hwyla to be inspecting it's nbt data.

**Comment by sweetsosweet** [comment]
Alright thanks, wow that was fast. I'll head over there now.
