### ISSUE TITLE
Suggestion: Armor images instead of numbers for entities?

### ISSUE THREAD

**Issue by sweetsosweet** [Darkhax-Minecraft/WAWLA#78]
Not an issue, just a little request. Is it possible to display entity armor information as images like the player armor hud? Similar to the health showing as hearts. Not a big deal, just nice visually.

**Comment by darkhax** [comment]
This is a good suggestion, but not so easy to do with the way Waila and Hwyla work. I am trying to make it so Wawla can run on all sorts of info mods that might not support images.
