### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by jneumann** [Darkhax-Minecraft/WAWLA#79]
Attached is the crash report when I try to start up my game with JourneyMap, JEI, and WAWLA loaded. If you need any other relevant information, let me know.

[crash-2017-06-27_18.46.08-client.txt](https://github.com/Darkhax-Minecraft/WAWLA/files/1107130/crash-2017-06-27_18.46.08-client.txt)

**Comment by darkhax** [comment]
This crash is caused by Forge updating and breaking some existing mods. Please use the [latest](https://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at/files/2441428) version of Wawla, it already has this fix in it.

**Comment by jneumann** [comment]
You rock!
