### ISSUE TITLE
[1.12] Mules and donkeys have no speed/jump display

### ISSUE THREAD

**Issue by zontargs** [Darkhax-Minecraft/WAWLA#82]
Probably due to mules and donkeys getting their own ID in 1.11, mules and donkeys don't display their speed and jumping stats.

I suspect 

if (data.entity instanceof EntityHorse) {

in wawla/plugins/vanilla/PluginHorse.java no longer returns true for mules and donkeys.

**Comment by darkhax** [comment]
Thanks! I will push an update out soon 😃
