### ISSUE TITLE
crash from looking at fairies from roots(1.12.2)

### ISSUE THREAD

**Issue by SDUBZ** [Darkhax-Minecraft/WAWLA#86]
Forge: 1.12.2-2582
wawla: 1.12.2-2.5.247
hwyla: 1.8.23-B38_1.12
roots: 2-0.104

crash report:
[crash-2018-01-04_14.50.25-client.txt](https://github.com/Darkhax-Minecraft/WAWLA/files/1602382/crash-2018-01-04_14.50.25-client.txt)

**Comment by darkhax** [comment]
This is an issue with roots.
