### ISSUE TITLE
.

### ISSUE THREAD

**Issue by joelkingg** [Darkhax-Minecraft/WAWLA#89]
.

**Comment by darkhax** [comment]
Hello, can you give me info on why you closed this issue?

**Comment by joelkingg** [comment]
I closed it because im thinking the issue isnt related to WAWLA as no point
in bothering the mod creator though it mentions your mod in the crash
report. My original issue was that im unable to create a bucket, i would
put the ingots in the crafting table but it crashes when i hover over the
bucket. It's weird as i have very few mods as well.

https://paste.ubuntu.com/p/2KHPpyP2Ny/
