### ISSUE TITLE
Data Missing: Horse Stats

### ISSUE THREAD

**Issue by artdude543** [Darkhax-Minecraft/WAWLA#93]
Seems the horse data or the rendering of the data is missing.

![image](https://user-images.githubusercontent.com/1885466/40873757-559034aa-665e-11e8-8df7-f28d2d56fa1e.png)

Not sure when this initially occurred. But versions currently used.
Relates to: https://github.com/DarkPacks/SevTech-Ages/issues/2320

Forge: 14.23.4.2705
Mod: 2.5.256

**Comment by darkhax** [comment]
For some reason the changes to the language file didn't get pushed. Should be fixed in the next release which will be on curse as soon as they approve it.
