### ISSUE TITLE
OOM when looking at Sky Compression's Rock Crusher

### ISSUE THREAD

**Issue by Efimero** [Darkhax-Minecraft/WAWLA#95]
WAWLA: 2.5.257
[WailaErrorOutput.txt](https://github.com/Darkhax-Minecraft/WAWLA/files/2343105/WailaErrorOutput.txt)

**Comment by darkhax** [comment]
Thanks for the report, I released [this](https://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at/files/2612231) version a few minutes ago which should fix your issue. Let me know how it goes.

**Comment by darkhax** [comment]
Ah, the curse team is at PAX so they're not reviewing files right now. [here](https://maven.mcmoddev.com/net/darkhax/wawla/Wawla-1.12.2/2.5.259/Wawla-1.12.2-2.5.259.jar) is the file from the build server.

**Comment by Efimero** [comment]
cool, thanks! it works like a charm :* <3
