### ISSUE TITLE
Server Crash on load

### ISSUE THREAD

**Issue by TheRealDadbeard** [Darkhax-Minecraft/WAWLA#97]
https://hastebin.com/uhopisopus.rb

MC: 1.12.1
Forge: 2759
Wawla: 2.5.260

**Comment by Foxgreat** [comment]
Same crash+

**Comment by boosterdev** [comment]
https://pastebin.com/raw/DQrm9S04

**Comment by darkhax** [comment]
This issue should be fixed, just waiting on curse to review. https://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at/files/2613883

**Comment by AdaraChristine** [comment]
I have the same error but cant use the Alpha in my pack due to twitch not loading it. Any ETA when it might be bumped up to beta or release?

**Comment by darkhax** [comment]
@AdaraChristine You can enable alpha builds in the twitch app settings. I've marked it as a release for you anyhow though.
